### ISSUE TITLE
odd error when attempting to swap through a univ3 pool on a local fork

### ISSUE THREAD

**Issue by 3commascapital** [zemse/hardhat-tracer#16]
got the following when trying to swap a uniswap v3 pool
```
✗ node_modules/.bin/hardhat trace --hash 0xb89c8ee689b95663128571e426b1608ded1263dcc72a18047e3a055f179a08cc --rpc http://localhost:8545
You are forking from block 14361020, which has less than 31 confirmations, and will affect Hardhat Network's performance.
Please use block number 14360994 or wait for the block to get 26 more confirmations.
Switched mainnet fork to block 14361020

node_modules/hardhat/src/internal/core/providers/http.ts:78
    const error = new ProviderError("HttpProviderError", -1);
                  ^
ProviderError: Errors encountered in param 1: Storage slot argument must have a length of 66 ("0x" + 32 bytes), but '0x0' has a length of 3
    at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at JsonRpcClient._send (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:346:39)
    at JsonRpcClient._perform (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:276:34)
    at JsonRpcClient.getStorageAt (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:56:17)
    at ForkStateManager.getContractStorage (node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkStateManager.ts:206:51)
    at VMDebugTracer._getContractStorage (node_modules/hardhat/src/internal/hardhat-network/stack-traces/vm-debug-tracer.ts:469:34)
    at VMDebugTracer._stepToStructLog (node_modules/hardhat/src/internal/hardhat-network/stack-traces/vm-debug-tracer.ts:312:39)
    at VMDebugTracer._stepHandler (node_modules/hardhat/src/internal/hardhat-network/stack-traces/vm-debug-tracer.ts:141:34)
    at node_modules/async-eventemitter/lib/AsyncEventEmitter.js:58:8
    at node_modules/async/internal/withoutIndex.js:9:16
```

**Comment by zemse** [comment]
This may be related to https://github.com/ethers-io/ethers.js/issues/2982

Can you try using the latest version of ethers?

**Comment by 3commascapital** [comment]
i did. thanks @zemse. unfortunately the same issue is occuring. i think it might be related to https://github.com/NomicFoundation/hardhat/issues/2672 can't say for sure though

**Comment by zemse** [comment]
Hey @3commascapital, are you still facing this problem?

**Comment by 3commascapital** [comment]
will check when next able
