### ISSUE TITLE
 printDebugTraceElseLogs err: TypeError: Cannot read properties of undefined (reading 'entries')

### ISSUE THREAD

**Issue by mhxw** [zemse/hardhat-tracer#17]
Using debug_tt on rpc failed, activating mainnet fork at block 12461683
The Hardhat Network tracing engine could not be initialized. Run Hardhat with --verbose to learn more.
```
Error in printDebugTraceElseLogs: TypeError: Cannot read properties of undefined (reading 'entries')
    at printDebugTrace (/Users/Projects/hardhat-tracer1/src/print/debug-trace.ts:31:66)
    at printDebugTraceOrLogs (/Users/Projects/hardhat-tracer1/src/print/index.ts:19:7)
    at SimpleTaskDefinition.action (/Users/Projects/hardhat-tracer1/src/tasks/trace.ts:82:22)
    at Environment._runTaskDefinition (/Users/Projects/debugger/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/Projects/debugger/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at main (/Users/Projects/debugger/node_modules/hardhat/src/internal/cli/cli.ts:256:5)
If you think the above error is a bug, please report it to https://github.com/zemse/hardhat-tracer/issues/new, meanwhile falling back to --logs:
```

**Comment by zemse** [comment]
Thanks for reporting, can you pls provide the entire cli command used, I'll look into this.

**Comment by mhxw** [comment]
Can I send you the response data after requesting debug_tracetransaction via rpc?

**Comment by mhxw** [comment]
> Thanks for reporting, can you pls provide the entire cli command used, I'll look into this.

Can I send you the response data after requesting debug_tracetransaction via rpc?

**Comment by zemse** [comment]
yep that should help

**Comment by zemse** [comment]
Can you please try [v2-beta](https://github.com/zemse/hardhat-tracer/tree/v2-beta) branch if it resolves this issue for you? The internal logic is rewritten to improve performance and features.

```
npm i hardhat-tracer@beta
```

**Comment by zemse** [comment]
Closing this since it should be resolved with the v2. If you are facing any issue feel free to reopen :)
