### ISSUE TITLE
trace fails, requests recorder object

### ISSUE THREAD

**Issue by gibsfinancedev** [zemse/hardhat-tracer#70]
```
TypeError: Cannot read properties of undefined (reading 'previousTraces')
    at SimpleTaskDefinition.action (./node_modules/hardhat-tracer/src/tasks/trace.ts:151:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Environment._runTaskDefinition (./node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Environment.run (./node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at async main (./node_modules/hardhat/src/internal/cli/cli.ts:323:7)
```
this appears to be the line
```
    debug("printing trace");
    await print(recorder.previousTraces[recorder.previousTraces.length - 1], {
      artifacts: hre.artifacts,
      tracerEnv: hre.tracer,
      provider: hre.ethers.provider,
    });
```
is there a peer dependency that is needed besides hh>2.22.5?

**Comment by zemse** [comment]
Thanks for reporting. I want to reproduce and fix this asap.

- Which chain network is this?
- It does appear, but just to confirm are you using latest hardhat (2.22.5) and hardhat-tracer (3.0.1)?
- Can you share the trace command?

**Comment by gibsfinancedev** [comment]
when i created a minimal reproducible, i was unable to replicate. i will investigate more and see if it is a piece of configuration that i am missing. and yes, those are the versions i am using

**Comment by 3commascapital** [comment]
and yes, those are the versions i am using

**Comment by zemse** [comment]
>  i will investigate more and see if it is a piece of configuration that i am missing.

If your repo is public I can try having a quick look.
